// Seed examples for the on-device fallback model (see model.js).
// Titles are written the way they appear on YouTube / tab titles, channel names included.
// Keep the two lists roughly the same size: the model assumes equal priors.

export const STUDY_EXAMPLES = [
  "Binary Search Introduction | Real Life Example | Iterative | Recursive | take U forward",
  "L1. Introduction to Linked List | Striver A2Z DSA Course",
  "Dynamic Programming full course for coding interviews freeCodeCamp.org",
  "Graph Algorithms for technical interviews full course",
  "Lecture 5: Arrays in C++ | Love Babbar DSA Supreme",
  "Recursion in one shot | Apna College",
  "Kadane's Algorithm | Maximum Subarray Sum | Finding and Printing",
  "Two Sum - Leetcode 1 - HashMap - Python NeetCode",
  "Sliding Window technique explained with examples",
  "System Design Interview: Design a URL shortener",
  "System design basics: load balancers, caching and CDNs",
  "Low Level Design of Parking Lot | LLD interview question",
  "Designing Data Intensive Applications book summary chapter 1",
  "Operating System full course | process scheduling | GATE CSE",
  "DBMS normalization 1NF 2NF 3NF BCNF with examples",
  "Computer Networks complete course | OSI model | TCP IP",
  "SQL joins explained inner left right outer join",
  "SQL interview questions for data analyst and backend roles",
  "Object oriented programming in Java | OOPs concepts | Kunal Kushwaha",
  "JavaScript tutorial for beginners full course",
  "TypeScript crash course in one video",
  "React JS tutorial | hooks useState useEffect explained",
  "Node.js and Express REST API project from scratch",
  "Next.js 15 full stack app with authentication",
  "Docker tutorial for beginners containers images volumes",
  "Kubernetes explained in 15 minutes | pods deployments services",
  "Git and GitHub for beginners crash course",
  "Linux command line basics for developers",
  "AWS cloud practitioner full course",
  "Machine learning course by Andrew Ng lecture 1",
  "Neural networks from scratch in Python",
  "Transformers and attention explained | deep learning",
  "Python for data science pandas numpy tutorial",
  "C++ STL complete tutorial vector map set",
  "Time and space complexity analysis big O notation",
  "Abdul Bari 2.1 Asymptotic notations big oh omega theta",
  "Merge sort algorithm explained with code",
  "Quick sort partition algorithm step by step",
  "Heap data structure and priority queue implementation",
  "Trie data structure | insert search delete",
  "Segment tree range queries | competitive programming",
  "Dijkstra shortest path algorithm with priority queue",
  "Topological sort using Kahn's algorithm BFS",
  "Union find disjoint set union path compression",
  "Bit manipulation tricks for coding interviews",
  "Codeforces Round 950 Div 2 editorial solutions",
  "LeetCode weekly contest 400 solutions explained",
  "How I cracked Google SDE interview preparation strategy",
  "Amazon SDE 1 interview experience and questions",
  "Placement preparation roadmap for final year CSE students",
  "Resume tips for software engineer freshers",
  "Mock coding interview with a senior engineer",
  "Behavioral interview questions for software engineers STAR method",
  "Striver SDE sheet day 3 arrays medium problems",
  "DSA roadmap 2025 complete guide hindi",
  "Arrays one shot in hindi | DSA for placements",
  "Placement ki taiyari kaise kare | complete strategy hindi",
  "Coding kaise seekhe beginners ke liye hindi",
  "Java full course in hindi Code With Harry",
  "Python tutorial hindi for beginners CodeWithHarry",
  "Web development full course hindi HTML CSS JavaScript",
  "GATE CSE theory of computation finite automata",
  "Discrete mathematics graph theory lecture",
  "Linear algebra for machine learning MIT OCW",
  "Probability and statistics lecture for engineers",
  "Compiler design lexical analysis parsing lecture",
  "Computer architecture pipelining and caches lecture",
  "Distributed systems lecture consensus raft paxos",
  "Database indexing B trees explained",
  "Redis caching strategies for backend engineers",
  "Kafka tutorial event streaming basics",
  "Microservices vs monolith architecture explained",
  "CAP theorem and consistency models explained",
  "Rate limiter design token bucket algorithm",
  "Design WhatsApp system design interview",
  "Design Instagram feed system design high level design",
  "Go programming language tutorial goroutines channels",
  "Rust programming ownership and borrowing explained",
  "Spring Boot tutorial REST API with MySQL",
  "Django tutorial build a blog application",
  "Flutter app development course for beginners",
  "Android development with Kotlin tutorial",
  "CSS flexbox and grid tutorial",
  "Tailwind CSS crash course",
  "GraphQL vs REST API explained",
  "OAuth 2.0 and JWT authentication explained",
  "Cybersecurity basics networking for ethical hacking course",
  "Regular expressions tutorial regex for developers",
  "Clean code principles and refactoring",
  "Design patterns in Java singleton factory observer",
  "SOLID principles explained with examples",
  "Unit testing with Jest tutorial",
  "CI CD pipeline with GitHub Actions tutorial",
  "Terraform infrastructure as code beginner tutorial",
  "VS Code tips and tricks for developers",
  "How the internet works DNS HTTP TLS explained",
  "Concurrency and multithreading in Java",
  "Memory management garbage collection explained",
  "Stack and queue implementation using arrays",
  "Binary tree traversals inorder preorder postorder",
  "Lowest common ancestor in binary search tree",
  "Longest common subsequence dynamic programming",
  "0/1 knapsack problem dynamic programming memoization",
  "N queens backtracking problem explained",
  "Matrix chain multiplication DP on partitions",
  "Monotonic stack next greater element",
  "Prefix sum and difference array technique",
  "String algorithms KMP pattern matching",
  "Rabin Karp string matching rolling hash",
  "Minimum spanning tree Kruskal and Prim",
  "r/leetcode how I went from 0 to 500 problems",
  "r/cscareerquestions offer negotiation advice for new grads",
  "r/developersIndia how to prepare for product based companies",
  "r/learnprogramming best way to learn data structures",
  "Stack Overflow how to reverse a linked list in python",
  "MDN Web Docs Array.prototype.map() JavaScript reference",
  "Python 3 documentation data structures",
  "React documentation quick start",
  "GeeksforGeeks detect cycle in a directed graph",
  "Medium understanding event loop in node.js",
  "Engineering blog how we scaled postgres to millions of users",
  "Hacker News show HN open source database written in rust",
  "Tech news: new JavaScript runtime released",
  "Wikipedia Dijkstra's algorithm",
  "Wikipedia hash table",
  "Coursera algorithms part 1 Princeton",
  "NPTEL programming data structures and algorithms using python",
  "MIT 6.006 introduction to algorithms lecture 1",
  "CS50 lecture 0 scratch Harvard",
  "Stanford CS229 machine learning lecture",
  "Aptitude preparation for placements quantitative reasoning",
  "Logical reasoning tricks for campus placement tests",
  "Technical interview HR round questions for freshers",
  "Open source contribution guide for beginners GSoC",
  "Build a compiler in C step by step",
  "Operating systems three easy pieces virtualization chapter"
];

export const DISTRACTION_EXAMPLES = [
  "Ultimate prank on my brother gone wrong",
  "Try not to laugh challenge impossible",
  "Funny moments compilation 2025",
  "My daily vlog | college life in Delhi",
  "Goa trip vlog with friends",
  "Street food tour of Old Delhi",
  "What I eat in a day vlog",
  "Roasting cringe Instagram reels",
  "Reacting to the funniest memes",
  "Dank Indian memes compilation",
  "Stand up comedy special full show",
  "Comedy sketch middle class family",
  "BB Ki Vines new episode",
  "CarryMinati roast video",
  "Triggered Insaan live stream",
  "MrBeast I spent 100 days in a circle",
  "Bigg Boss latest episode full fight",
  "Shark Tank India best pitches",
  "Kapil Sharma show best moments",
  "Pushpa 2 official trailer",
  "Animal movie best scenes",
  "Full movie hindi dubbed action",
  "New South Indian movie 2025 hindi dubbed",
  "Top 10 Netflix series to binge this weekend",
  "Stranger Things season 5 trailer",
  "Mirzapur season 3 all episodes explained",
  "Marvel movies ranked worst to best",
  "Movie review and ending explained",
  "Arijit Singh romantic songs jukebox",
  "Latest Punjabi songs 2025 Diljit Dosanjh",
  "Bollywood party songs nonstop",
  "Lofi romantic mashup slowed and reverb",
  "Taylor Swift official music video",
  "Honey Singh new song lyrical video",
  "90s evergreen hindi songs",
  "Trending Instagram reels songs",
  "Dance cover on trending song",
  "Bhojpuri video song new",
  "BGMI live rush gameplay",
  "Free Fire headshot montage",
  "GTA 5 funny moments",
  "Minecraft but every block is random",
  "Valorant ranked gameplay road to radiant",
  "Fortnite chapter 5 live event",
  "Techno Gamerz GTA 5 episode",
  "Total Gaming Free Fire live",
  "Clash of Clans best attack strategy town hall 16",
  "Chess speedrun blitz rating climb",
  "PUBG mobile best moments",
  "IPL 2025 highlights CSK vs MI",
  "India vs Pakistan full match highlights",
  "Virat Kohli best cover drives",
  "Football skills and goals compilation",
  "WWE Raw highlights",
  "Fantasy cricket team prediction dream11",
  "Cricket live score commentary",
  "Celebrity wedding inside video",
  "Bollywood gossip latest news",
  "Salman Khan interview controversy",
  "Shah Rukh Khan best dialogues",
  "Instagram influencer drama explained",
  "YouTube drama and controversy explained",
  "Unboxing the new iPhone camera test for vlogging",
  "Gadget haul unboxing and giveaway",
  "Room tour aesthetic makeover",
  "Morning routine aesthetic",
  "Get ready with me outfit ideas",
  "Makeup tutorial party look",
  "Fashion haul try on",
  "Cooking the spiciest noodles challenge",
  "24 hours challenge in a car",
  "Asking strangers funny questions",
  "Relationship advice podcast episode",
  "Celebrity podcast with Bollywood actor",
  "Motivational speech compilation sigma edit",
  "Anime fight scenes edit",
  "One Piece episode 1100 reaction",
  "Naruto best moments amv",
  "Satisfying video compilation to relax",
  "ASMR eating sounds mukbang",
  "Cute cats and dogs funny videos",
  "Astrology horoscope today predictions",
  "Horror story animated in hindi",
  "Real ghost videos caught on camera",
  "Mystery facts you didn't know",
  "Top 10 richest people in the world",
  "Luxury cars collection tour",
  "Superbike ride vlog",
  "Travel vlog Manali snowfall",
  "Wedding dance performance sangeet",
  "Bhai bahen ki ladai funny video",
  "School life vs college life comedy",
  "Hostel life comedy sketch",
  "Web series official teaser",
  "Behind the scenes of the movie shoot",
  "Box office collection day 5",
  "Reddit r/memes hot",
  "Reddit r/funny top posts",
  "Reddit r/IndianCricket match thread",
  "Reddit r/BollyBlindsNGossip",
  "Reddit r/gaming what are you playing this weekend",
  "Reddit r/AskReddit what is the weirdest thing",
  "Reddit r/pics amazing sunset",
  "Reddit r/relationships advice needed",
  "Twitter trending celebrity feud",
  "Amazon great Indian festival sale deals on shoes",
  "Flipkart big billion days offers",
  "Myntra end of season sale",
  "Zomato food offers near me",
  "Swiggy instamart order",
  "Online shopping best deals kurta",
  "Latest smartphone price leaks and rumours",
  "Entertainment news today",
  "Viral video today",
  "Election rally speech live",
  "Breaking news live headlines",
  "Horoscope and tarot reading weekly",
  "Dating app tips",
  "Fantasy novel audiobook chapter 12",
  "Sitcom best scenes compilation",
  "Game of Thrones season recap",
  "Kdrama romantic scenes",
  "Hindi serial latest episode",
  "Cartoon episodes for kids",
  "Magic tricks revealed",
  "Pranks on girlfriend gone emotional",
  "Couple vlog anniversary surprise",
  "Family vlog Diwali celebration",
  "Rap battle diss track",
  "Music concert live full show",
  "Guitar cover of trending song",
  "Instagram reels compilation part 5",
  "YouTube shorts funny compilation"
];

export function seedExamples() {
  return [
    ...STUDY_EXAMPLES.map(text => ({ text, label: "study" })),
    ...DISTRACTION_EXAMPLES.map(text => ({ text, label: "distraction" }))
  ];
}
